cc_test(
    name = "glfw_run_test",
    srcs = [
        "glfw_run_test.cc",
    ],
    deps = [
        "@usr//:glfw3",
        "@python_glad//:c_glad",
    ],
)

cc_binary(
    name = "glfw_build_test",
    srcs = [
        "glfw_build_test.cc",
    ],
    deps = [
        "@usr//:glfw3",
        "@python_glad//:c_glad",
    ],
)
